parser: "@typescript-eslint/parser"
parserOptions:
	ecmaVersion: 2020
	sourceType: "module"
	ecmaFeatures: 
		jsx: true
	settings:
		react:
			version: "detect"
	extends:
		- "plugin:react/recommended"
		- "plugin:@typescript-eslint/recommended"
		- "prettier/@typescript-eslint"
		- "plugin:prettier/recommended"
	rules:
		"@typescript-eslint/no-use-before-define": 0
		'react/jsx-no-undef': 'error'
		'react/jsx-uses-react': 'error'
		'react/jsx-uses-vars': 'error'
