env:
    browser: true
    es2020: true
extends:
    - "eslint:recommended"
    - "plugin:@typescript-eslint/recommended"
	- "prettier/@typescript-eslint"
	- "plugin:prettier/recommended"
    - "plugin:react/recommended"
globals:
    Atomics: readonly
    SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
    ecmaFeatures:
        jsx: true
    ecmaVersion: 2020
    sourceType: module
plugins:
    - react
	- "@typescript-eslint"
	- "prettier"
rules: 
	"@typescript-eslint/no-use-before-define": 0
